export const Palavras = [
    
        /*"abacaxi", "abelhas", "abismo", "abóbora", "acertar", "acordar", "adorado", "afastar", "afogado", "agitado",
        "alegado", "algemas", "alimentar", "almofada", "altitude", "amarelo", "amizade", "ampliação", "andarilho", "anelado",
        "angústia", "animado", "anotado", "apanhar", "apertar", "aplicado", "apontar", "armazém", "arquear", "arranjo",
        "arrepio", "artesan", "aspirar", "assaltar", "assustar", "atacado", "atender", "atitude", "atração", "autoria",
        "avançar", "averiguar", "balanço", "banhado", "banquete", "barulho", "bastante", "beleza", "bizarro", "bloqueio",
        "boiando", "borracha", "bravura", "brilhante", "brindado", "brisa", "bronze", "buzinas", "cabedal", "cabine",
        "cabeça", "cachorro", "cadeira", "caminhar", "camiseta", "campanha", "canário", "cantiga", "capricho", "caravela",
        "carbono", "cardume", "careta", "carregar", "cartão", "cativar", "cavernas", "celeste", "cenoura", "certeza",
        "chamada", "charme", "chatear", "chegada", "choro", "chuveiro", "ciclone", "cinderela", "circular", "clarão",
        "coelho", "cofre", "colinas", "colorir", "combate", "comédia", "compasso", "completo", "compra", "computar",
        "conduzir", "confuso", "conquista", "conselho", "consumo", "contorno", "conversa", "coragem", "cordeiro", "corredor",
        "costeiro", "crescer", "cristal", "crônico", "cultura", "dançar", "deixado", "delícia", "depressa", "descanso",
        "deserto", "desgosto", "despertar", "desporto", "destino", "detalhe", "diagrama", "diamante", "difuso", "dignidade",
        "dilúvio", "dinheiro", "dissonar", "divisão", "doçura", "doloroso", "dourado", "dúvida", "educado", "efeito",
        "elástico", "elefante", "elevado", "embalar", "emendar", "empatia", "empresta", "encantar", "energia", "enigmático",
        "enlace", "enorme", "entusiasmo", "envolto", "equilíbrio", "escarlate", "escondido", "escritor", "escudo", "espacial",
        "esperar", "esporte", "estágio", "estrela", "estrondo", "etiqueta", "evapora", "exalar", "exato", "exótico",
        "expressa", "extremo", "fascinar", "fechado", "felicidade", "ferrovia", "festival", "fidelidade", "figueira", "filosofia",
        "flauta", "foguete", "fomeado", "formiga", "forte", "fortuna", "fragilidade", "fronteira", "fuga", "fulgente",
        "fundado", "galáxia", "gambito", "garrafa", "gavião", "generoso", "gentil", "gigante", "girar", "goleiro",
        "golfinho", "gostoso", "gramado", "gravado", "grinalda", "guardiã", "habilidoso", "harmonia", "havia", "herança",
        "horizonte", "hospedar", "humanizar", "humilde", "ideias", "ignorado", "iluminado", "imaginar", "imortal", "impresso",
        "inaugurar", "incrível", "infância", "informar", "iniciar", "inovador", "insônia", "inspirado", "interesse", "intuição",
        "inverno", "invicto", "irradiar", "isolado", "itinerário", "jornada", "juventude", "labirinto", "lacrado", "ladeira",
        "lanterna", "lateral", "lavanda", "lealdade", "lembrança", "lentidão", "leopardo", "levitar", "liberdade", "licença",
        "limpidez", "liquidez", "litoral", "livramento", "locomoção", "lúdico", "luminoso", "manchado", "maratona", "marfim",
        "martelo", "medalha", "melodia", "memória", "mercado", "mestre", "milagre", "minério", "mirante", "mistério",
        "montagem", "motivação", "mudança", "natural", "navalha", "navegante", "nebuloso", "negócio", "neve", "nostalgia",
        "noturno", "nublado", "objetivo", "obrigado", "oceânico", "ofuscar", "olhar", "ondulado", "opaco", "opinião",
        "oração", "orvalho", "ouvinte", "padeiro", "página", "palhaço", "pancada", "pássaro", "paz", "pedestre",
        "pelicano", "penhasco", "perdido", "perfeito", "persiana", "pescador", "picolé", "pijama", "pinguim", "pirata",
        "planeta", "plástico", "poderoso", "polarizado", "polvilho", "portaria", "prazer", "prezado", "primavera", "privilégio",
        "profundo", "progresso", "projeto", "prosa", "quadrado", "quebra", "quente", "quimera", "quintal", "quiosque",
        "radiante", "rajada", "raposa", "rebeldia", "reboliço", "recordar", "recriar", "refletir", "refrigério", "regra",
        "reino", "relâmpago", "relicário", "remoto", "rendição", "resgate", "resistente", "responsa", "retrato", "revolta",
        "riqueza", "ritmado", "robusto", "romântico", "rosa", "rotina", "safado", "salvador", "sanfona", "satisfação",
        "sombra", "sonhador", "sossego", "subida", "sucesso", "surpresa", "talento", "temperado", "tendência", "terremoto",
        "tesouro", "tigre", "tolerante", "trabalho", "travesseiro", "trilha", "tropical", "turquesa", "uivante", "unicórnio",
        "universo", "utópico", "vagalume", "valioso", "variedade", "vassoura", "veículo", "velocidade", "vento", "vermelho",
        "viagem", "viciante", "vila", "vitrina", "viver", "voador", "vontade", "xilofone", "zangado", "zebra"*/

        
        "abana", "acaso", "achar", "amigo", "andar", "animo", "apito", "arroz", "atomo", "aviso",
        "banco", "barco", "beber", "bicho", "bloco", "bomba", "bravo", "breve", "brisa", "burro",
        "caber", "cacho", "cansa", "carro", "ceder", "ciclo", "claro", "cobre", "corpo", "custo",
        "dança", "dedo", "dente", "dicas", "doido", "dorme", "dorso", "duelo", "duplo", "durar",
        "ecoar", "elite", "entra", "esfor", "etapa", "exato", "falar", "fardo", "feroz", "festa",
        "junto", "largo", "lento", "linda", "livro", "lugar", "magia", "massa", "matar", "medir",
        "morar", "mundo", "nadar", "nariz", "nobre", "norma", "nuvem", "obvio", "olhar", "ousar",
        "pagar", "parte", "perto", "piano", "poder", "ponto", "prato", "quase", "quilo", "rabia",
        "rampa", "resto", "risco", "rocha", "roupa", "saber", "sente", "subir", "tarde", "traco"
          
          
    ]
